SELECT * FROM customer_behavior.customer;

-- ======================================================
-- Analytics queries for `customer` table (MySQL-ready)
-- Paste the whole block into MySQL Workbench and run.
-- ======================================================

/* ----------------------------------------------------------------
Q1. What is the total revenue generated by male vs. female customers?
-----------------------------------------------------------------*/
SELECT
  gender,
  ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

-- ----------------------------------------------------------------
-- Q2. Which customers used a discount but still spent more than the
--     average purchase amount?
-- ----------------------------------------------------------------
SELECT *
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

-- ----------------------------------------------------------------
-- Q3. Which are the top 5 products with the highest average review rating?
-- NOTE: If review_rating is stored as text, we CAST it to DECIMAL.
-- ----------------------------------------------------------------
SELECT
  item_purchased,
  ROUND(AVG(CAST(review_rating AS DECIMAL(5,2))), 2) AS average_product_rating
FROM customer
-- exclude NULL or empty ratings if needed:
WHERE review_rating IS NOT NULL AND TRIM(review_rating) <> ''
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

-- ----------------------------------------------------------------
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
-- ----------------------------------------------------------------
SELECT
  shipping_type,
  ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;

-- ----------------------------------------------------------------
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
--     between subscribers and non-subscribers.
-- ----------------------------------------------------------------
SELECT
  subscription_status,
  COUNT(customer_id) AS total_customers,
  ROUND(AVG(purchase_amount), 2) AS avg_spend,
  ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- ----------------------------------------------------------------
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- ----------------------------------------------------------------
SELECT
  item_purchased,
  ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate_percent
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate_percent DESC
LIMIT 5;

-- ----------------------------------------------------------------
-- Q7. Segment customers into New, Returning, and Loyal based on their total number
--     of previous purchases, and show the count of each segment.
--     (New = previous_purchases = 1, Returning = 2-10, Loyal = >10)
-- ----------------------------------------------------------------
SELECT
  customer_segment,
  COUNT(*) AS number_of_customers
FROM (
  SELECT
    customer_id,
    CASE
      WHEN previous_purchases = 1 THEN 'New'
      WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
      WHEN previous_purchases > 10 THEN 'Loyal'
      ELSE 'Unknown'
    END AS customer_segment
  FROM customer
) AS seg
GROUP BY customer_segment
ORDER BY FIELD(customer_segment, 'Loyal', 'Returning', 'New', 'Unknown');

-- ----------------------------------------------------------------
-- Q8. What are the top 3 most purchased products within each category?
-- Approach: aggregate counts then rank per category using MySQL user variables.
-- ----------------------------------------------------------------
-- Step A: Build counts per (category, item_purchased), ordered by category and count desc
-- Step B: Use user variables to assign row numbers per category, then filter <= 3
SELECT category, item_purchased, total_orders
FROM (
  SELECT
    s.category,
    s.item_purchased,
    s.total_orders,
    @rn := IF(@prev_cat = s.category, @rn + 1, 1) AS rn,
    @prev_cat := s.category
  FROM (
    SELECT
      category,
      item_purchased,
      COUNT(*) AS total_orders
    FROM customer
    GROUP BY category, item_purchased
    ORDER BY category, total_orders DESC
  ) AS s
  CROSS JOIN (SELECT @rn := 0, @prev_cat := '') vars
) ranked
WHERE rn <= 3
ORDER BY category, total_orders DESC;

-- ----------------------------------------------------------------
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)
--     also likely to subscribe?
-- ----------------------------------------------------------------
SELECT
  subscription_status,
  COUNT(*) AS repeat_buyers_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers_count DESC;

-- ----------------------------------------------------------------
-- Q10. What is the revenue contribution of each age group?
-- (Assumes there is an 'age_group' column; otherwise create buckets with CASE)
-- ----------------------------------------------------------------
SELECT
  age_group,
  ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
